[package]
name = "echor_derived"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.94"
assert_cmd = "2.0.16"
predicates = "3.1.2"
pretty_assertions = "1.4.1"
